Fix asyncio changes in Python 3.12
Problem observed:
 - failing tests buildbot.test.integration.test_worker_proxy
 - failing with stack traces like

[ERROR]
Traceback (most recent call last):
  File "C:\P\.venv\Lib\site-packages\twisted\internet\defer.py", line 1996, in _inlineCallbacks
    result = context.run(
  File "C:\P\.venv\Lib\site-packages\twisted\python\failure.py", line 519, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\P\buildbot\master\buildbot\test\integration\interop\test_transfer.py", line 197, in test_no_exist_multiple_file_upload
    yield self.setup_config_single_step(step)
  File "C:\P\.venv\Lib\site-packages\twisted\internet\defer.py", line 1996, in _inlineCallbacks
    result = context.run(
  File "C:\P\.venv\Lib\site-packages\twisted\python\failure.py", line 519, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\P\buildbot\master\buildbot\test\integration\interop\test_transfer.py", line 130, in setup_config_single_step
    yield self.setup_master(c)
  File "C:\P\.venv\Lib\site-packages\twisted\internet\defer.py", line 1996, in _inlineCallbacks
    result = context.run(
  File "C:\P\.venv\Lib\site-packages\twisted\python\failure.py", line 519, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\P\buildbot\master\buildbot\test\integration\test_worker_proxy.py", line 159, in setup_master
    yield super().setup_master(config_dict, startWorker,
  File "C:\P\.venv\Lib\site-packages\twisted\internet\defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\P\buildbot\master\buildbot\test\util\integration.py", line 249, in setup_master
    self.w = Worker(
  File "C:\P\buildbot\worker\buildbot_worker\pb.py", line 667, in __init__
    proxy_endpoint = clientFromString(reactor, proxy_connection_string)
  File "C:\P\.venv\Lib\site-packages\twisted\internet\endpoints.py", line 2137, in clientFromString
    kwargs = _clientParsers[name](*args, **kwargs)
  File "C:\P\.venv\Lib\site-packages\twisted\internet\endpoints.py", line 1861, in _parseClientTCP
    kwargs["port"] = int(args[1])
builtins.ValueError: invalid literal for int() with base 10: 'test_worker_proxy_stdout_11208.txt'

But real problem seems to be in start of proxy

Exception Raised: There is no current event loop
Traceback (most recent call last):
  File "C:\P\buildbot\master\buildbot\test\integration\test_worker_proxy.py", line 92, in run_proxy
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\events.py", line 693, in get_event_loop
    warnings.warn('There is no current event loop',
DeprecationWarning: There is no current event loop

Fix is inspired by https://github.com/danigm/jupyter_client/blob/9c1ddf4a50a71181e60be7045d954a3fafa91357/jupyter_client/utils.py#L14-L29